baseURL = 'https://reboplim.com/'
languageCode = 'en-us'
title = 'Ryan Lim'
disableHugoGeneratorInject = true
disableKinds = ["404", "robotstxt", "rss", "sitemap", "taxonomy", "term"]

[params]
    description = 'Personal website of Ryan Lim.'
    author = 'Ryan Lim'
